# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Orchestrate or schedule a set of job
# go010
jobs:
  configure_infrastructure: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout       
      - add_ssh_keys:
          fingerprints: ["e6:20:1e:e1:9c:dd:a1:ae:66:29:ca:ab:b9:4d:45:04"] # =================== > You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            #apk add --update ansible 
             apt update -y
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main4.yml 

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
