# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Orchestrate or schedule a set of job
# go010
jobs:
  configure_infrastructure: 
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout       
      - add_ssh_keys:
          fingerprints: ["59:98:8e:04:2a:4b:b1:b5:9c:fd:e5:46:d8:d3:fe:a1"] # =================== > You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            apt update -y
            apt install ansible -y
            
            
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main4.yml --private-key=./cp.pem

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
